## Write a program that generates 10 random numbers with values between 1-100.
import random as rm
def odd(list_in):
    # function for the removal of even numbers from a list
    i = 0
    list_out = []
    while i < len(list_in):
        if (list_in[i]%2) == 1:
        # function can be inverted by changing the comparative value to 0
            list_out = list_out + [list_in[i]]
        i = i + 1
    return list_out

def main():
    ten_numbers = [rm.randint(0, 100) for x in range(0, 10)]
# list comprehension form of for loop. An instance of x = randint(...) is created for each item in range(...)
    print(f"\nList of random ten numbers generated by comprehensive for loop: \n {ten_numbers}\nSame list, even numbers removed with while loop:\n {odd(ten_numbers)}\n")
    print(f"same goal output accomplished in one equation, using for loops:\n {[x for x in [rm.randint(0, 100) for x in range(0, 10)] if x%2 != 0]}\n")
main()